Enabled Spark notebooks to run in repo's Docker container.
aerospike-examples/interactive-notebooks pull request #36
Opened 2021-11-28 18:03 UTC by neelp-git

2021-12-02 22:54 UTC, kirmatty26 approved these changes

2021-12-02 23:27 UTC, arrowplum commented
I have not run it but from a cursory glance LGTM

2021-12-02 23:27 UTC, arrowplum approved these changes

2021-12-03 00:45 UTC, rahul-aerospike commented on notebooks/spark/other_notebooks/AerospikeSparkPythonJSONSQL.ipynb
> +    "#### Tested with Spark connector 3.1.0, Java 8, Apache Spark 3.0.2, Python 3.7"
Spark connector **3.2.0**

2021-12-03 00:46 UTC, rahul-aerospike requested changes
LGTM. Just a small change.

2021-12-03 06:19 UTC, neelp-git commented
@rahul-aerospike Yes, we can claim tested with 3.2.0 because it does run successfully -thanks. Will update and merge.

2021-12-03 20:56 UTC, merged